refactor(ci): INFRA-112 move others domains tests to core workflow file with condition

diff --git a/.github/workflows/_nodejs.condo.core.tests.yml b/.github/workflows/_nodejs.condo.core.tests.yml
--- a/.github/workflows/_nodejs.condo.core.tests.yml
+++ b/.github/workflows/_nodejs.condo.core.tests.yml
@@ -85,19 +85,31 @@ jobs:
           [[ $(jobs | wc -l | tr -d ' ') != '2' ]] && exit 2
           sleep 3
 
-          # TESTS
-          yarn workspace @app/condo test --workerIdleMemoryLimit="50%" --testTimeout=15000 --runInBand --forceExit --silent=false --verbose --bail --testPathPattern '/domains/${{ inputs.domain_name }}/schema/(.*)[.]test.js$' 2>&1 > 'condo.${{ inputs.domain_name }}.tests.log'
-
-          # SPECS
-          if [ -n "$(find apps/condo/domains/${{ inputs.domain_name }} -name '*spec.js' 2>/dev/null)" ]; then
-            yarn workspace @app/condo test --workerIdleMemoryLimit="50%" --testTimeout=15000 --runInBand --forceExit --silent=false --verbose --bail --testPathPattern '/domains/${{ inputs.domain_name }}/(.*)[.]spec.js$' 2>&1 > 'condo.${{ inputs.domain_name }}.specs.log'
+          if [ "${{ inputs.domain_name }}" != "others" ]; then
+            # TESTS
+            yarn workspace @app/condo test --workerIdleMemoryLimit="50%" --testTimeout=15000 --runInBand --forceExit --silent=false --verbose --bail --testPathPattern '/domains/${{ inputs.domain_name }}/schema/(.*)[.]test.js$' 2>&1 > 'condo.${{ inputs.domain_name }}.tests.log'
+            # SPECS
+            if [ -n "$(find apps/condo/domains/${{ inputs.domain_name }} -name '*spec.js' 2>/dev/null)" ]; then
+              yarn workspace @app/condo test --workerIdleMemoryLimit="50%" --testTimeout=15000 --runInBand --forceExit --silent=false --verbose --bail --testPathPattern '/domains/${{ inputs.domain_name }}/(.*)[.]spec.js$' 2>&1 > 'condo.${{ inputs.domain_name }}.specs.log'
+            else
+              echo "Files matching (.*)[.]spec.js in directory apps/condo/domains/${{ inputs.domain_name }} not found! Skipping..."
+            fi 
+            # Note: we need to stop background worker! because packages tests use the same redis queue
+            kill $(jobs -p) || echo 'background worker and dev server is already killed!'
+            killall node || echo 'no node processes'
           else
-            echo "Files matching (.*)[.]spec.js in directory apps/condo/domains/${{ inputs.domain_name }} not found! Skipping..."
+            # TESTS
+            yarn workspace @app/condo test --workerIdleMemoryLimit="50%" --testTimeout=15000 --runInBand --forceExit --silent=false --verbose --bail --testPathPattern '/schema/(.*)[.]test.js$' --testPathIgnorePatterns='/domains/(organization|user|scope|property|acquiring|billing|miniapp|banking|ticket|meter|contact|resident|notification|common)/' 2>&1 > condo.others.tests.log
+            yarn workspace @app/condo test --workerIdleMemoryLimit="50%" --testTimeout=15000 --runInBand --forceExit --silent=false --verbose --bail --testPathPattern '(.*)[.]test.js$' --testPathIgnorePatterns='/schema/(.*)[.]test.js$' 2>&1 > condo.5.test.others.log
+            # SPECS
+            yarn workspace @app/condo test --workerIdleMemoryLimit="50%" --testTimeout=15000 --runInBand --forceExit --silent=false --verbose --bail --testPathPattern '(.*)[.]spec.js$' --testPathIgnorePatterns='/domains/(organization|user|scope|property|acquiring|billing|miniapp|banking|ticket|meter|contact|resident|notification|common)/' 2>&1 > condo.others.specs.log
+            # Note: we need to stop background worker! because packages tests use the same redis queue
+            kill $(jobs -p) || echo 'background worker and dev server is already killed!'
+            killall node || echo 'no node processes'
+            
+            yarn jest ./packages/keystone --maxWorkers=2
+            yarn workspace @app/condo lint-schema
           fi
-        
-          # Note: we need to stop background worker! because packages tests use the same redis queue
-          kill $(jobs -p) || echo 'background worker and dev server is already killed!'
-          killall node || echo 'no node processes'
         env:
           DATABASE_URL: ${{ matrix.database }}
           NODE_ENV: development
